#pragma once

#define ID_MAINMENU 101
#define ID_MAINMENU_FILE_NEW 102
#define ID_MAINMENU_FILE_OPEN 103
#define ID_MAINMENU_FILE_SAVE 104
#define ID_MAINMENU_FILE_SAVE_AS 105
#define ID_MAINMENU_FILE_EXIT 106

#define ID_MAINMENU_EDIT_COPYPOSES 110
#define ID_MAINMENU_EDIT_PASTEPOSES 111
#define ID_MAINMENU_EDIT_APPLYPOSETOALL 112
#define ID_MAINMENU_EDIT_POSITION 113
#define ID_MAINMENU_EDIT_ROTATION 114
#define ID_MAINMENU_EDIT_SCALE 115
#define ID_MAINMENU_EDIT_PARENT 116
#define ID_MAINMENU_EDIT_SELECTALL 117
#define ID_MAINMENU_EDIT_SELECTNONE 118

#define ID_MAINMENU_VIEW_ANIMWINDOW 120
#define ID_MAINMENU_VIEW_RESETCAM 121
#define ID_MAINMENU_VIEW_SETFPSVIEW 122
#define ID_MAINMENU_VIEW_BGCOLOR 123
#define ID_MAINMENU_VIEW_GRID 124

#define ID_MAINMENU_LIMBS_ADD 130
#define ID_MAINMENU_LIMBS_REPLACE 131
#define ID_MAINMENU_LIMBS_DEL 132
#define ID_MAINMENU_LIMBS_PIVOT 133

#define ID_MAINMENU_RAGDOLL_COPY 140
#define ID_MAINMENU_RAGDOLL_PASTE 141
#define ID_MAINMENU_RAGDOLL_ADDPARTICLE 142
#define ID_MAINMENU_RAGDOLL_DELETEPARTICLE 143
#define ID_MAINMENU_RAGDOLL_ENABLECOLLISION 144
#define ID_MAINMENU_RAGDOLL_SETCONNECTDISTANCE 145
#define ID_MAINMENU_RAGDOLL_CONNECT 146
#define ID_MAINMENU_RAGDOLL_UNCONNECT 147
#define ID_MAINMENU_RAGDOLL_MODE 148
#define ID_MAINMENU_RAGDOLL_PREVIEW 149
#define ID_MAINMENU_RAGDOLL_SETPARENT 150
#define ID_MAINMENU_RAGDOLL_SETMOVEPOINT 151
#define ID_MAINMENU_RAGDOLL_UNSETMOVEPOINT 152
#define ID_MAINMENU_RAGDOLL_REMMOVEPOINT 153
#define ID_MAINMENU_RAGDOLL_DISABLECOLLISION 154
